### ISSUE TITLE
about the meshgraphormer architecture problem

### ISSUE THREAD

**Issue by zhangzhenyu-zzy** [microsoft/MeshGraphormer#1]
Hello, I want to know two things,
1. I want to prove whether the input in the meshgraphormer framework and the information in the attention mechanism are as I drew the picture
![IMG_20210908_200139](https://user-images.githubusercontent.com/81757380/132506906-971bf749-49f1-43e1-a5e5-4dad2abc1eb5.jpg)

2. I want to know that grid features are obtained by extracting features through CNN. Its dimension is 49×1024. It is not marked in the paper that it uses upsampling. How did it transform from 49×1024 to 49×2051?
![image](https://user-images.githubusercontent.com/81757380/132507044-1c766428-726e-4fbc-9822-83d6a7e12516.png)

**Comment by kevinlin311tw** [comment]
Q1: There are (49+14+431) input tokens. All tokens have 2051-Dim.

Q2: We apply MLP for the transform. In Sec 4.1, we mentioned that we apply MLP to make the size of all input tokens consistent. After that, all input tokens have 2051-Dim.

**Comment by zhangzhenyu-zzy** [comment]
thank you very much！
