### ISSUE TITLE
How to get the 'azureml' file?

### ISSUE THREAD

**Issue by PomIsBest** [microsoft/MeshGraphormer#17]
![azureml](https://user-images.githubusercontent.com/45503953/161420923-46202279-c48e-42ba-b0f9-35bd34df99dc.jpg)
Greeting!
When I want to evaluate the code， I meet an error "No module named 'azureml'. I check the root and couldn't find the file.
I would like to know how to get this file for the correct run.
Thanks for your great work!

**Comment by kevinlin311tw** [comment]
You may run `pip install --upgrade azureml-core` to fix it

**Comment by PomIsBest** [comment]
Thank you very much！
 I have now solved the problem and appreciate your patience in answering！
