### ISSUE TITLE
body mesh reconstruction test

### ISSUE THREAD

**Issue by zhaishengfu** [microsoft/MeshGraphormer#3]
thanks for sharing this wonderful project!
I see that you tell us how to testhand , but not test body , so how can we test body mesh resconstruction with our own image or videos?

**Comment by CocoaPebble** [comment]
Hi Zhai, have you found a way to test body mesh reconstruction on videos or pictures? Can you provide some ideas to achieve?

**Comment by zhaishengfu** [comment]
> Hi Zhai, have you found a way to test body mesh reconstruction on videos or pictures? Can you provide some ideas to achieve?

Yes, see this question [](https://github.com/microsoft/MeshGraphormer/issues/5)

**Comment by kevinlin311tw** [comment]
Hi all, the inference code has been added. Please check the example and give a try!
