### ISSUE TITLE
not good result ??

### ISSUE THREAD

**Issue by zhaishengfu** [microsoft/MeshGraphormer#5]
https://user-images.githubusercontent.com/7630101/137278281-d38daeb7-6d1d-4762-96cb-eb256ea19f74.mp4

I change from your code and write my own test script to inference from video, but the result seems not good as previous videos shows.

the core code is :
```
        # forward-pass
        pred_camera, pred_3d_joints, pred_vertices_sub2, pred_vertices_sub, pred_vertices = Graphormer_model(images, smpl, mesh_sampler)
        # obtain 3d joints, which are regressed from the full mesh
        pred_3d_joints_from_smpl = smpl.get_h36m_joints(pred_vertices)
        pred_3d_joints_from_smpl = pred_3d_joints_from_smpl[:,cfg.H36M_J17_TO_J14,:]

        # obtain 2d joints, which are projected from 3d joints of smpl mesh
        pred_2d_joints_from_smpl = orthographic_projection(pred_3d_joints_from_smpl, pred_camera)
```

the skeleton is pred_2d_joints_from_smpl . do i misunderstand something?

**Comment by segerenj** [comment]
Hey @zhaishengfu did you figure out a solution? Indeed, inference scripts would be helpful.

**Comment by zhaishengfu** [comment]
> Hey @zhaishengfu did you figure out a solution? Indeed, inference scripts would be helpful.
below is  the script for my inference. put it under src/tools/ directory.
[run_gphmer_bodymesh_inference.zip](https://github.com/microsoft/MeshGraphormer/files/7524413/run_gphmer_bodymesh_inference.zip)

I guess the reason being bad is due to the bad result of 2d keypoints detection

**Comment by liushanyuan18** [comment]
> > Hey @zhaishengfu did you figure out a solution? Indeed, inference scripts would be helpful.
> 
> below is the script for my inference. put it under src/tools/ directory. [run_gphmer_bodymesh_inference.zip](https://github.com/microsoft/MeshGraphormer/files/7524413/run_gphmer_bodymesh_inference.zip)
> 
> I guess the reason being bad is due to the bad result of 2d keypoints detection

您好！感谢您的run_gphmer_bodymesh_inference.py代码，但是里面有一个函数visualize_reconstruction_inference不存在，想请问这个函数代码可以share一下吗

**Comment by kevinlin311tw** [comment]
Hi all, the inference code has been added. Please check the example and give a try!

@zhaishengfu, thanks for the video results! I think there are two possible reasons: (1) The size of the target person is not normalized. If the size is not similar to that in our training, it will not work well. (2) As the person moves, the person may not locate at the center of the input image.
