### ISSUE TITLE
evaluate H36m on protocol2

### ISSUE THREAD

**Issue by asw91666** [microsoft/MeshGraphormer#7]
Hi! I have a question about evaluation.
human36m protocol2 execute on subject9,11 with 64 frame steps.
but i think your code is on 5 frame steps. 
ex) _000001.jpg, _000006.jpg, _000011.jpg, ...

Could you share 64 frame steps evaluation code?

**Comment by kevinlin311tw** [comment]
Sorry, we don't have the 64-frame step evaluation. We follow the evaluation protocol used in the literature. Specifically, we adopt evaluation code from [Convolutional Mesh Regression for Single-Image Human Shape Reconstruction, CVPR 2019](https://github.com/nkolot/GraphCMR/)
